#!/bin/bash

while getopts "f:d:al:" opt; do
    case $opt in
        f) filename="$OPTARG"
        ;;
        d) foldername="$OPTARG"
        ;;
        a) execute_all=true
        ;;
        l) logfilename="$OPTARG"
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        ;;
    esac
done

if [ ! -z "$logfilename" ]; then
    if [ ! -z "$execute_all" ]; then
        for folder in data/*; do
            for file in "$folder"/*; do
                if [[ "$file" != *"decoded"* && "$file" != *"encoded"* ]]; then
                    ./bin/main "$file" verify >> "$logfilename"
                fi
            done
        done
    elif [ ! -z "$filename" ]; then
        ./bin/main "$filename" verify >> "$logfilename"
    elif [ ! -z "$foldername" ] && [ -z "$execute_all" ]; then
        for file in "$foldername"/*; do
            if [[ "$file" != *"decoded"* && "$file" != *"encoded"* ]]; then
                ./bin/main "$file" verify >> "$logfilename"
            fi
        done
    else
        echo "Please specify either a filename or a foldername."
    fi
else
    if [ ! -z "$execute_all" ]; then
        for folder in data/*; do
            for file in "$folder"/*; do
                if [[ "$file" != *"decoded"* && "$file" != *"encoded"* ]]; then
                    ./bin/main "$file" verify
                fi
            done
        done
    elif [ ! -z "$filename" ]; then
        ./bin/main "$filename" verify
    elif [ ! -z "$foldername" ] && [ -z "$execute_all" ]; then
        for file in "$foldername"/*; do
            if [[ "$file" != *"decoded"* && "$file" != *"encoded"* ]]; then
                time ./bin/main "$file" verify
            fi
        done
    else
        echo "Please specify either a filename or a foldername."
    fi
fi